### ISSUE TITLE
ERR: Could not open requirements file while running setup.py

### ISSUE THREAD

**Issue by iretex** [RanFeldesh/streamlit-examples#2]
The requirements file for streamlit needs to be renamed to "requirements_streamlit_simple.txt" to match the expected filename in the setup.py line 131 - 136.

**Comment by RanFeldesh** [comment]
Thank you @iretex  for highlighting this for me and everyone,

Indeed I might have changed the file name recently, but I haven't change the name in the `setup.py` file. Indeed I missed that.


The solution could be a 1-line PR: 
* Change the name accordingly in [line 131](https://github.com/RanFeldesh/streamlit-examples/blob/main/setup/setup.py#L131) of setup.py. From `streamlit_simple` to `simple_streamlit`. 
* Show that the setup works following this change. 

If you or anyone is interested in creating this PR, I'd be happy to review and approve.

Thank you for highlighting this.

**Comment by iretex** [comment]
Thanks very much for the feedback. I have implemented the changes and raised a PR.
